### PR TITLE
Fixed MsAzurePatchFilterWorkaround to not clear the entire list

### LINKED ISSUE #668: Patch replace operation with MS Azure patch-filter-expression workaround deletes other items in a list
I have the Azure workaround enabled
```java
.patchConfig(PatchConfig.builder()
		.supported(true)
		.activateMsAzureWorkaround(true)
		.build())
``` 
And there is an existing user with some multivalue complex attribute for example
```
"emails": [
  {
    "type": "work",
    "primary": true,
    "value": "john@work.com"
  },
  {
    "type": "home",
    "primary": false,
    "value": "john@home.com"
  }
]
``` 
When this patch request is received
```
{
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:PatchOp"
  ],
  "Operations": [
    {
      "op": "replace",
      "path": "emails[type eq \"work\"].value",
      "value": "updated@work.com"
    }
  ]
}
``` 
Then the emails attribute is updated to 
``` 
"emails": [
  {
    "type": "work",
    "primary": false,
    "value": "updated@work.com"
  }
]
``` 
The home email was removed.
It does not matter if the filter `type eq \"work\"` matches an existing item or not.

### PR DESCRIPTION
**Pull request by ondrejzivotsky**
Fixed MsAzurePatchFilterWorkaround to not clear the entire list during a Replace operation

fixes #668

### CODE REVIEW

File: scim-sdk-server/src/main/java/de/captaingoldfish/scim/sdk/server/patch/workarounds/msazure/MsAzurePatchFilterWorkaround.java [hunk 1]
```diff
@@ -71,8 +71,8 @@ public class MsAzurePatchFilterWorkaround extends PatchWorkaround
   public boolean shouldBeHandled(PatchConfig patchConfig, ResourceType resourceType, PatchRequestOperation operation)
   {
     Optional<String> path = operation.getPath();
-    return patchConfig.isMsAzureFilterWorkaroundActive() && !PatchOp.REMOVE.equals(operation.getOp())
-           && path.isPresent() && operation.getValues().size() == 1 && path.get().matches(".*?\\[.*?]\\..*");
+    return patchConfig.isMsAzureFilterWorkaroundActive() && PatchOp.ADD.equals(operation.getOp()) && path.isPresent()
```
Comment (ondrejzivotsky) [inline scim-sdk-server/src/main/java/de/captaingoldfish/scim/sdk/server/patch/workarounds/msazure/MsAzurePatchFilterWorkaround.java:74]: `MsAzureFilterWorkaround` can be used only for `add` operation. Using it for `replace` operation causes the list to be cleared.

File: scim-sdk-server/src/main/java/de/captaingoldfish/scim/sdk/server/patch/PatchTargetHandler.java [hunk 2]
```diff
@@ -907,6 +910,21 @@ private boolean handleMultiComplexSubAttributePath(ArrayNode multiValued,
     if (path.getChild() != null && matchingComplexNodes.isEmpty())
     {
       // a filter expression was present and no matches were found e.g. (emails[type eq "work"].type)
+      if (patchConfig.isMsAzureFilterWorkaroundActive() && PatchOp.REPLACE.equals(patchOp)
```
Comment (ondrejzivotsky) [inline scim-sdk-server/src/main/java/de/captaingoldfish/scim/sdk/server/patch/PatchTargetHandler.java:913]: Implementation of Replace operation for MS Entra (Azure)

File: scim-sdk-server/src/test/java/de/captaingoldfish/scim/sdk/server/patch/PatchAddResourceHandlerTest.java [hunk 3]
```diff
@@ -2364,81 +2364,6 @@ public void testMsAzureBehaviourForMultivaluedComplexTypesWithFilterInPathExpres
...
-   *   "meta" : {
-   *     "lastModified" : "2023-02-05T11:56:25.8049737+01:00"
-   *   }
-   * }
-   * </pre>
-   *
-   * if the user did have the email "erika@mustermann.de" before
-   */
-  @Test
-  public void testMsAzureBehaviourForMultivaluedComplexTypesWithFilterInPathExpression2Replace()
```
Comment (ondrejzivotsky) [inline scim-sdk-server/src/test/java/de/captaingoldfish/scim/sdk/server/patch/PatchAddResourceHandlerTest.java:2409]: These tests showed that the patch couldn't work to replace a single value in a list.

If you define emails as list:
```
    User user = User.builder().emails(Arrays.asList(
            Email.builder().primary(true).value("erika@mustermann.de").build(),
            Email.builder().primary(false).value("erika-secondary@mustermann.de").build()
    )).build();
```
This will fail:  `Assertions.assertEquals(2, patchedUser.getEmails().size(), patchedUser.toPrettyString());` - only one email remains there.
